version: '3'

services:
  # ui:
  #   build: ./ui
  #   ports:
  #     - 8080:80
  db:
    build: ./db
    ports:
      - 27017:27017
  # api:
  #   build: ./api
  #   links:
  #     - db
  #   ports:
  #     - 8081:3000